#########################################################################
# Title:            Cloudbox Community: FlexGet                        #
# Author(s):        javi11                                              #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  derbenni/docker-flexget                             #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: 'Setting CloudFlare DNS Record'
  include_role:
    name: cloudflare-dns
  vars:
    record: flexget
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: flexget
    state: absent

- name: Create flexget directories
  file: 'path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}'
  with_items:
    - /opt/flexget

- name: Create and start container
  docker_container:
    name: flexget
    image: wiserain/flexget
    pull: yes
    published_ports:
      - '127.0.0.1:3539:3539'
    env:
      UMASK_SET: 022
      UMASK: 002
      PUID: '{{ uid }}'
      PGID: '{{ gid }}'
      VIRTUAL_HOST: 'flexget.{{ user.domain }}'
      VIRTUAL_PORT: 3539
      LETSENCRYPT_HOST: 'flexget.{{ user.domain }}'
      LETSENCRYPT_EMAIL: '{{ user.email }}'
      FG_LOG_LEVEL: 'debug'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/flexget:/config'
      - '/mnt:/mnt'
      - '/mnt/local:/data'
    labels:
      'com.github.cloudbox.cloudbox_managed': 'true'
    networks:
      - name: cloudbox
        aliases:
          - flexget
    purge_networks: yes
    restart_policy: always
    state: started
